export const BulletinKeys = {
    LOAD_BULLETINS_SUCCESS: "LOAD_BULLETINS_SUCCESS",
    SAVE_BULLETIN_SUCCESS: "SAVE_BULLETIN_SUCCESS"
}

export const UserKeys = {
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS"
}

export const AdminPermissionsKeys = {
    LOAD_ADMIN_PERMISSIONS_SUCCESS: "LOAD_ADMIN_PERMISSIONS",
    LOAD_ROLE_INFORMATION_SUCCESS: "LOAD_ROLE_INFORMATION_SUCCESS",
    REMOVE_MEMBER_FROM_ROLE_SUCCESS: "REMOVE_MEMBER_FROM_ROLE_SUCCESS",
    DISMISS_REMOVE_MEMBER_FROM_ROLE_SUCCESS: "DISMISS_REMOVE_MEMBER_FROM_ROLE_SUCCESS",
    ADD_MEMBER_TO_ROLE_SUCCESS: "ADD_MEMBER_TO_ROLE_SUCCESS",
    DISMISS_ADD_MEMBER_TO_ROLE_SUCCESS: "DISMISS_ADD_MEMBER_TO_ROLE_SUCCESS"
}