export const BulletinKeys = {
    LOAD_BULLETINS_SUCCESS: "LOAD_BULLETINS_SUCCESS",
    SAVE_BULLETIN_SUCCESS: "SAVE_BULLETIN_SUCCESS"
}

export const UserKeys = {
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS"
}

export const AdminPermissionsKeys = {
    LOAD_ADMIN_PERMISSIONS_SUCCESS: "LOAD_ADMIN_PERMISSIONS",
    LOAD_ROLE_INFORMATION_SUCCESS:  "LOAD_ROLE_INFORMATION_SUCCESS"
}